In [1]:
import torch

## Tensor Shaping
### reshape: Change Tensor Shape
contiguous + view = reshape

In [2]:
x = torch.FloatTensor([[[1,2],
                      [3,4]],
                     [[5,6],
                     [7,8]],
                     [[9,10],
                      [11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [3]:
# 차원이 하나인 벡터로 변환
print(x.reshape(12))
print(x.reshape(-1))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [4]:
# 매트릭스로 변환
print(x.reshape(3, 4))
print(x.reshape(3, -1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [6]:
# 텐서로 변환
print(x.reshape(3,1,4))
print(x.reshape(-1,1,4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [7]:
print(x.reshape(3,2,2,1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


### squeeze: Remove dimension which has only one element.
자동적으로 1인 차원을 대상으로 하기 때문에 인수 불필요

In [10]:
x = torch.FloatTensor([[[1,2],
                      [3,4]]])
print(x.size())

torch.Size([1, 2, 2])


In [12]:
print(x.squeeze())
print(x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [13]:
# 특정 차원 제거
print(x.squeeze(0).size())
print(x.squeeze(1).size()) # 1이 없을 경우 똑같은 텐서 리턴

torch.Size([2, 2])
torch.Size([1, 2, 2])


### unsqueeze: Insert dimension at certain index.

In [15]:
x = torch.FloatTensor([[1,2],
                      [3,4]])
print(x.size())

torch.Size([2, 2])


In [19]:
print(x.unsqueeze(2))
print(x.unsqueeze(-1))
print(x.reshape(2,2,-1))

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
