# How to use GPU
같은 디바이스 안의 텐서끼리만 연산 가능

In [1]:
import torch
import torch.nn as nn

## Convert to CUDA tensor: cuda()
복제해서 해당 디바이스에 저장하는 것으로 기존 변수는 그대로 존재

In [2]:
x = torch.cuda.FloatTensor(2,2)
x

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [3]:
x = torch.FloatTensor(2, 2)
x

tensor([[5.3054e-06, 3.0871e-41],
        [0.0000e+00, 0.0000e+00]])

In [4]:
x.cuda()

tensor([[5.3054e-06, 3.0871e-41],
        [0.0000e+00, 0.0000e+00]], device='cuda:0')

In [5]:
d = torch.device('cuda:0')

In [6]:
x.cuda(device=d)

tensor([[5.3054e-06, 3.0871e-41],
        [0.0000e+00, 0.0000e+00]], device='cuda:0')

In [7]:
x.device

device(type='cpu')

## Convert to CUDA tensor: to()
복제해서 해당 디바이스에 저장하는 것으로 기존 변수는 그대로 존재



In [8]:
x.to(device=d)

tensor([[5.3054e-06, 3.0871e-41],
        [0.0000e+00, 0.0000e+00]], device='cuda:0')

In [9]:
x.device

device(type='cpu')

## Covert to CPU tensor from CUDA tensor

In [10]:
x = torch.cuda.FloatTensor(2,2)

In [11]:
# 첫번째 방법
x = x.cpu()

In [12]:
# 두번째 방법
d =  torch.device('cpu')
x = x.to(d)

In [13]:
x.device

device(type='cpu')

## Move model from CPU to GPU
Copy가 아니라 Move

In [14]:
def print_params(model):
  for p in model.parameters():
    print(p)

In [15]:
linear = nn.Linear(2,2)

print_params(linear)

Parameter containing:
tensor([[0.6770, 0.3602],
        [0.0124, 0.5930]], requires_grad=True)
Parameter containing:
tensor([-0.0331,  0.4459], requires_grad=True)


In [16]:
# to GPU
linear = linear.cuda()

print_params(linear)

Parameter containing:
tensor([[0.6770, 0.3602],
        [0.0124, 0.5930]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.0331,  0.4459], device='cuda:0', requires_grad=True)


In [17]:
# to CPU
linear = linear.cpu()

print_params(linear)

Parameter containing:
tensor([[0.6770, 0.3602],
        [0.0124, 0.5930]], requires_grad=True)
Parameter containing:
tensor([-0.0331,  0.4459], requires_grad=True)


In [18]:
# to GPU
d = torch.device('cuda:0')
linear = linear.to(d)

print_params(linear)

Parameter containing:
tensor([[0.6770, 0.3602],
        [0.0124, 0.5930]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.0331,  0.4459], device='cuda:0', requires_grad=True)


In [19]:
# nn.Module은 device 가 없다.
linear.device

AttributeError: ignored

## Tricks

In [21]:
x = torch.cuda.FloatTensor(2,2)

In [22]:
x.new(2,2) # x와 같은 타입이면서, 같은 디바이스에 있는 텐서 생성

tensor([[1.0842e-19, 1.2572e+00],
        [1.2448e-02, 5.9301e-01]], device='cuda:0')

In [23]:
torch.zeros_like(x) 

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [24]:
torch.ones_like(x)  

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [25]:
list(linear.parameters())[0].new(2,2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')