In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [3]:
# 간단한 머신러닝 구현
import sklearn
print(sklearn.__version__)

0.22.1


In [4]:
# 1. 데이터 로딩
iris = load_iris()
print(type(iris))
# iris.head()  -> impossible : 타입이 다르기 때문

sklearn.utils.Bunch

In [6]:
keys = iris.keys()
print('dataset keys: ', keys)
# target : 정답(숫자로 구성), target_names : 이름, DESCR : 피쳐 설명

dataset keys:  dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [12]:
print('key data\n', iris.data)
print('*'*50)
print('key target\n', iris.target)
print('*'*50)
print('key target_names\n', iris.target_names)
print('*'*50)
print('key DESCR\n', iris.DESCR)
print('*'*50)
print('key feature_names\n', iris.feature_names)
print('*'*50)
print('key filename\n', iris.filename)

key data
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [

In [13]:
# feature 데이터셋 확인
iris_data = iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
# 레이블(결정값/ 타켓/ 클래스) 확인
iris_label = iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
# 데이터 프레임 변환
iris_df = pd.DataFrame(iris_data, columns = iris.feature_names)
iris_df['target'] = iris_label
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [26]:
# 학습 데이터, 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=20)
print('train data\n', X_train)
print('train label\n', y_train)
print('test data\n', X_test)
print('test label\n', y_test)

train data
 [[5.7 3.  4.2 1.2]
 [5.6 3.  4.1 1.3]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.9 2.5 4.5 1.7]
 [6.  3.4 4.5 1.6]
 [4.9 3.  1.4 0.2]
 [6.4 3.2 4.5 1.5]
 [7.4 2.8 6.1 1.9]
 [5.7 2.8 4.5 1.3]
 [6.1 2.6 5.6 1.4]
 [4.9 3.6 1.4 0.1]
 [6.7 3.1 4.4 1.4]
 [6.3 3.3 4.7 1.6]
 [4.7 3.2 1.3 0.2]
 [5.4 3.9 1.7 0.4]
 [5.  3.3 1.4 0.2]
 [5.7 2.5 5.  2. ]
 [5.1 3.8 1.9 0.4]
 [6.4 2.8 5.6 2.2]
 [6.2 3.4 5.4 2.3]
 [5.4 3.4 1.5 0.4]
 [6.3 3.3 6.  2.5]
 [6.  2.2 4.  1. ]
 [5.6 2.9 3.6 1.3]
 [5.6 3.  4.5 1.5]
 [4.5 2.3 1.3 0.3]
 [5.1 3.4 1.5 0.2]
 [5.5 2.4 3.8 1.1]
 [6.2 2.9 4.3 1.3]
 [5.8 2.6 4.  1.2]
 [5.6 2.5 3.9 1.1]
 [6.7 3.1 4.7 1.5]
 [6.5 2.8 4.6 1.5]
 [5.7 2.9 4.2 1.3]
 [5.1 3.3 1.7 0.5]
 [6.2 2.2 4.5 1.5]
 [6.3 2.3 4.4 1.3]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.4 3.  4.5 1.5]
 [5.5 2.3 4.  1.3]
 [6.1 3.  4.6 1.4]
 [5.1 3.8 1.5 0.3]
 [5.3 3.7 1.5 0.2]
 [6.4 3.2 5.3 2.3]
 [5.5 3.5 1.3 0.2]
 [4.8 3.1 1.6 0.2]
 [5.  2.  3.5 1. ]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]


In [27]:
# 학습을 위한 알고리즘(학습기)
iris_dtc = DecisionTreeClassifier(random_state=20)
iris_dtc.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=20, splitter='best')

In [28]:
# 예측(Prediction) 수행
prediction = iris_dtc.predict(X_test)
print('y_test\n', y_test)
print('prediction\n', prediction)

y_test
 [0 1 1 2 1 1 2 0 2 0 2 1 2 0 0 2 0 1 2 1 1 2 2 0 1 1 1 0 2 2]
prediction
 [0 1 1 2 1 1 2 0 2 0 2 1 1 0 0 2 0 1 2 1 1 2 2 0 1 1 1 0 2 1]


In [37]:
# 예측 정확도 평가
from sklearn.metrics import accuracy_score
print('예측 정확도 :',accuracy_score(y_test, prediction))

예측 정확도 : 0.9333333333333333


In [38]:
# 데이터 프레임 형태 활용 방법
iris_df = pd.DataFrame(iris_data, columns = iris.feature_names)
iris_df['target'] = iris_label
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [39]:
# 피처와 레이블 나누기
feature_df = iris_df.iloc[:,:-1]
label_df = iris_df.iloc[:,-1]
display(feature_df)
display(label_df)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [48]:
# 학습 데이터, 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(feature_df, label_df, test_size=0.2, random_state=11)
print('train data\n', X_train)
print('train label\n', y_train)
print('test data\n', X_test)
print('test label\n', y_test)
print(type(X_train), type(X_test), type(y_train), type(y_test))

train data
      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
120                6.9               3.2                5.7               2.3
122                7.7               2.8                6.7               2.0
49                 5.0               3.3                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
76                 6.8               2.8                4.8               1.4
13                 4.3               3.0                1.1               0.1
81                 5.5               2.4                3.7               1.0
91                 6.1               3.0                4.6               1.4
80                 5.5               2.4                3.8               1.1

[120 rows x 4 columns]
train label
 0      0
120   

In [50]:
# 학습을 위한 알고리즘(학습기)
iris_dtc = DecisionTreeClassifier(random_state=20, criterion='gini')
iris_dtc.fit(X_train, y_train)

# 예측(Prediction) 수행
prediction = iris_dtc.predict(X_test)
print('y_test\n', y_test)
print('prediction\n', prediction)

# 예측 정확도 평가
from sklearn.metrics import accuracy_score
print('예측 정확도 :',accuracy_score(y_test, prediction))

y_test
 112    2
145    2
133    2
56     1
111    2
9      0
65     1
15     0
30     0
63     1
119    2
62     1
84     1
113    2
139    2
41     0
103    2
66     1
110    2
142    2
69     1
2      0
22     0
51     1
12     0
11     0
149    2
75     1
16     0
85     1
Name: target, dtype: int32
prediction
 [2 2 1 2 2 0 1 0 0 1 1 1 1 2 2 0 2 1 2 2 1 0 0 1 0 0 2 1 0 2]
예측 정확도 : 0.8666666666666667


In [51]:
# 학습을 시킬 때 테스트 데이터 세트를 이용하지 않고 학습 데이터만으로 예측한다면?

# 데이터 세트 분할없이 가져오기
bad_iris = load_iris()
train_data = bad_iris.data
train_label = bad_iris.target

# 학습을 위한 분류 모델
bad_iris_clf = DecisionTreeClassifier()
bad_iris_clf.fit(train_data, train_label)

# 잘못된 예측
pred = bad_iris_clf.predict(train_data)
print('예측 정확도: ', accuracy_score(train_label, pred))

예측 정확도:  1.0


### 교차 검증 (Cross Validation)
- KFold 방식

In [52]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

from sklearn.model_selection import KFold

import pandas as pd
import numpy as np

In [55]:
fold_iris = load_iris()
features = fold_iris.data
labels = fold_iris.target

fold_df_clf = DecisionTreeClassifier()

In [56]:
# 5개의 폴드 세트를 분리하여 각 폴드 세트별 정확도를 담을 리스트 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('iris shape: ', features.shape)

iris shape:  (150, 4)


In [66]:
n_iter = 0

for train_idx, test_idx in kfold.split(features):
   #  print(train_idx, test_idx)
    X_train, X_test = features[train_idx], features[test_idx]
    # print(X_test)
    
    y_train, y_test = labels[train_idx], labels[test_idx]
    # print(y_test)
    
    # 학습을 진행
    fold_df_clf.fit(X_train, y_train)
    
    # 예측
    fold_pred = fold_df_clf.predict(X_test)
    
    # 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, fold_pred), 4)
    print('\n{} 교차검증 정확도: {}, 학습 데이터 크기 : {}, 검증 데이터 크기 : {}'.format(n_iter,accuracy, X_train.shape[0], X_test.shape[0]))
    cv_accuracy.append(accuracy)
    
print('\n 평균검증 정확도: ', np.mean(cv_accuracy))


1 교차검증 정확도: 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

2 교차검증 정확도: 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

3 교차검증 정확도: 0.8667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

4 교차검증 정확도: 0.9333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

5 교차검증 정확도: 0.7667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

 평균검증 정확도:  0.9133400000000002


- Stratified KFold : 불균형한 분포도를 가진 레이블 데이터 집합을 위한 KFold 방식
    - 레이블의 분포를 먼저 고려한 뒤 이 분포와 동일하게 학습과 검증 데이터 세트로 분할
    - 분류 분석에서만 사용 가능

In [67]:
# 기존 KFold의 문제점 다시 한번 확인
kfold_iris_data = load_iris()

In [70]:
# print("\n", kfold_iris_data)
kfold_iris_data_df = pd.DataFrame(data=kfold_iris_data.data, columns=kfold_iris_data.feature_names)
kfold_iris_data_df['target'] = kfold_iris_data.target
print('vale_counts: \n', kfold_iris_data_df['target'].value_counts())

vale_counts: 
 2    50
1    50
0    50
Name: target, dtype: int64


In [71]:
kfold_iris_data_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [85]:
kfold_iris = KFold(n_splits=3)
cnt_iter = 0

for train_idx, test_idx in kfold_iris.split(kfold_iris_data_df):
    # print(train_idx, test_idx)
    cnt_iter += 1
    label_train = kfold_iris_data_df['target'].iloc[train_idx]
    label_test = kfold_iris_data_df['target'].iloc[test_idx]
    # print(label_test)
    print('교차검증: {}'.format(cnt_iter))
    print('학습 레이블 데이터 분포: \n', label_train.value_counts())
    print('검증 레이블 데이터 분포: \n', label_test.value_counts())
    

교차검증: 1
학습 레이블 데이터 분포: 
 2    50
1    50
Name: target, dtype: int64
검증 레이블 데이터 분포: 
 0    50
Name: target, dtype: int64
교차검증: 2
학습 레이블 데이터 분포: 
 2    50
0    50
Name: target, dtype: int64
검증 레이블 데이터 분포: 
 1    50
Name: target, dtype: int64
교차검증: 3
학습 레이블 데이터 분포: 
 1    50
0    50
Name: target, dtype: int64
검증 레이블 데이터 분포: 
 2    50
Name: target, dtype: int64


In [86]:
# 레이블 값의 분포 반영하기 위한 StratifiedKFold 방식 사용
from sklearn.model_selection import StratifiedKFold

In [87]:
skfold_iris = StratifiedKFold(n_splits=3)
cnt_iter = 0

for train_idx, test_idx in skfold_iris.split(kfold_iris_data_df, kfold_iris_data_df['target']):
    # print(train_idx, test_idx)
    cnt_iter += 1
    label_train = kfold_iris_data_df['target'].iloc[train_idx]
    label_test = kfold_iris_data_df['target'].iloc[test_idx]
    # print(label_test)
    print('교차검증: {}'.format(cnt_iter))
    print('학습 레이블 데이터 분포: \n', label_train.value_counts())
    print('검증 레이블 데이터 분포: \n', label_test.value_counts())

교차검증: 1
학습 레이블 데이터 분포: 
 2    34
1    33
0    33
Name: target, dtype: int64
검증 레이블 데이터 분포: 
 1    17
0    17
2    16
Name: target, dtype: int64
교차검증: 2
학습 레이블 데이터 분포: 
 1    34
2    33
0    33
Name: target, dtype: int64
검증 레이블 데이터 분포: 
 2    17
0    17
1    16
Name: target, dtype: int64
교차검증: 3
학습 레이블 데이터 분포: 
 0    34
2    33
1    33
Name: target, dtype: int64
검증 레이블 데이터 분포: 
 2    17
1    17
0    16
Name: target, dtype: int64


In [96]:
# 붓꽃 데이터 세트에서 Stratified KFold를 이용하여 교차검증을 진행하고 평균 정확도 확인(random state=100)
cv_accuracy=[]

skfold_iris = StratifiedKFold(n_splits=3)
cnt_iter = 0

for train_idx, test_idx in skfold_iris.split(kfold_iris_data_df, kfold_iris_data_df['target']):
    # print(train_idx, test_idx)
    cnt_iter += 1
    features_train = kfold_iris_data_df.iloc[:,:-1].iloc[train_idx]
    features_test = kfold_iris_data_df.iloc[:,:-1].iloc[test_idx]
    # print(features_train)
    label_train = kfold_iris_data_df['target'].iloc[train_idx]
    label_test = kfold_iris_data_df['target'].iloc[test_idx]
    # print(label_test)
    
    # 학습을 진행
    clf = DecisionTreeClassifier(random_state=100)
    clf.fit(features_train, label_train)
    
    # 예측
    pred = clf.predict(features_test)
    
    # 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(label_test, pred), 4)
    print('\n{} 교차검증 정확도: {}, 학습 데이터 크기 : {}, 검증 데이터 크기 : {}'.format(n_iter,accuracy, X_train.shape[0], X_test.shape[0]))
    cv_accuracy.append(accuracy)
    
print('\n 평균검증 정확도: ', np.mean(cv_accuracy))


9 교차검증 정확도: 0.98, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

10 교차검증 정확도: 0.92, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

11 교차검증 정확도: 0.96, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

 평균검증 정확도:  0.9533333333333333
