In [1]:
import torch

## Slicing and Concatenation
### Indexing and Slicing

In [3]:
x = torch.FloatTensor([[[1,2], 
                       [3,4]],
                      [[5,6], 
                       [7,8]],
                      [[9,10],
                       [11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [4]:
# 같은 표현
print(x[0])
print(x[0, :])
print(x[0, : , :])

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


In [6]:
print(x[ : ,0, : ])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


range로 접근했을 때, 차원의 수는 변하지 않는다. dimension reduction이 생기지 않는다.

*인덱스로만 접근하면 dimension reduction이 발생*

In [7]:
print(x[1:3, : , : ].size())
print(x[:, :1, :].size())
print(x[:, :-1, :].size())

torch.Size([2, 2, 2])
torch.Size([3, 1, 2])
torch.Size([3, 1, 2])


### split: Split tensor to desirable shapes.
해당 차원을 기재한 사이즈(적은 숫자)로 쪼개기

In [18]:
x = torch.FloatTensor(14,4)

In [19]:
splits = x.split(5, dim=0)

for s in splits:
    print(s.size())

torch.Size([5, 4])
torch.Size([5, 4])
torch.Size([4, 4])


### chunk: Split tensor to number of chunks.
해당 차원을 기재한 개수로 쪼개기

In [13]:
chunks = x.chunk(3, dim=0)

for c in chunks:
    print(c.size())

torch.Size([5, 4])
torch.Size([5, 4])
torch.Size([4, 4])


In [20]:
chunks

(tensor([[ 1.3556e-19,  5.0746e+31,  7.5338e+28,  6.1687e+16],
         [ 3.1436e-12,  1.3563e-19,  1.3563e-19,  1.3563e-19],
         [ 4.1294e-08,  3.7607e-14,  4.7339e+30,  5.4329e-40],
         [ 2.2493e-40,  2.3510e-38, -1.0340e-25,  2.0054e-38],
         [ 3.2907e-31,  7.9033e-43,  3.3041e-31,  7.9033e-43]]),
 tensor([[3.2832e-42, 0.0000e+00,        nan,        nan],
         [6.1533e-39, 7.3125e-34, 0.0000e+00, 0.0000e+00],
         [7.1920e+28, 2.9425e+26, 1.8040e+28, 3.4740e-12],
         [2.9767e+29, 1.2125e+04, 7.1846e+22, 2.4176e-12],
         [7.7781e+31, 1.8515e+28, 9.1041e-12, 6.2609e+22]]),
 tensor([[4.7428e+30, 6.0362e+28, 7.7783e+31, 5.0849e+31],
         [1.6040e+02, 6.9783e+22, 2.1127e-19, 7.0376e+28],
         [1.8970e+31, 7.2251e+28, 2.8231e+23, 1.2707e+31],
         [7.0076e+22, 4.3063e+21, 1.8970e+31, 1.1838e+33]]))

### index_select: Select elements by using dimension index.

In [21]:
x = torch.FloatTensor([[[1,1],
                        [2,2]],
                       [[3,3],
                        [4,4]],
                       [[5,5],
                        [6,6]]])
indice = torch.LongTensor([2,1])
print(x.size())

torch.Size([3, 2, 2])


In [22]:
y = x.index_select(dim=0, index=indice)
print(y)
print(y.size())

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


### cat: Concatenation of multiple tensors in the list.

In [23]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
y = torch.FloatTensor([[10,11,12],
                       [13,14,15],
                       [16,17,18]])
print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [24]:
z = torch.cat([x,y], dim=0)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [25]:
z = torch.cat([x,y], dim=-1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


### stack: Stacking of multiple tensors in the list.
=> 차원이 하나 더 생김

In [26]:
z = torch.stack([x,y])
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


In [27]:
# Specify the dimension (Default=0)
z = torch.stack([x,y], dim=-1)
print(z)
print(z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


**Implement 'stack' function by using 'cat'.**

In [28]:
# z = torch.stack([x,y])
z = torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


**Useful Trick: Merge results from iterations**

데이터 양이 상당할 때 함수에 데이터 일부를 나눠서 대입하게 되는데 그때 유용하게 사용 가능

In [29]:
result = []
for i in range(5):
    x = torch.FloatTensor(2,2)
    result += [x]
    
result = torch.stack(result)
result.size()

torch.Size([5, 2, 2])